/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tykni9794
 */
public class FrmPizzaForm extends javax.swing.JFrame {

    /**
     * Creates new form FrmMacaroonCostForm
     */
    public FrmPizzaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblItem1 = new javax.swing.JLabel();
        txtDiameterInput = new javax.swing.JTextField();
        btnCalcCost = new javax.swing.JButton();
        lblTaxesAns = new javax.swing.JLabel();
        lblSubtotalAns = new javax.swing.JLabel();
        lblGrandAns = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        lblImage.setToolTipText("");

        lblTitle.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 0));
        lblTitle.setText("The Party Pizza");

        lblDesc.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(255, 0, 0));
        lblDesc.setAlignmentX(0.5F);
        lblDesc.setPreferredSize(new java.awt.Dimension(416, 14));

        lblItem1.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        lblItem1.setForeground(new java.awt.Color(255, 0, 0));
        lblItem1.setText("Diameter of Pizza(cm):");

        btnCalcCost.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        btnCalcCost.setText("Calculate");
        btnCalcCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcCostActionPerformed(evt);
            }
        });

        lblTaxesAns.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        lblTaxesAns.setForeground(new java.awt.Color(255, 0, 0));
        lblTaxesAns.setText("Taxes(13%): ");

        lblSubtotalAns.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        lblSubtotalAns.setForeground(new java.awt.Color(255, 0, 0));
        lblSubtotalAns.setText("Subtotal:");

        lblGrandAns.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        lblGrandAns.setForeground(new java.awt.Color(255, 0, 0));
        lblGrandAns.setText("Grand Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblImage)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblItem1)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTaxesAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSubtotalAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGrandAns, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDiameterInput, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addGap(52, 52, 52)
                                .addComponent(btnCalcCost)
                                .addGap(27, 27, 27)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItem1)
                    .addComponent(btnCalcCost)
                    .addComponent(txtDiameterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSubtotalAns)
                .addGap(18, 18, 18)
                .addComponent(lblTaxesAns)
                .addGap(18, 18, 18)
                .addComponent(lblGrandAns)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcCostActionPerformed

        int pizzaDiameter = Integer.parseInt(txtDiameterInput.getText());

        double subtotal;
        
        if(pizzaDiameter <= 0)
        {
        subtotal = 0;
        }
        else
        {
            subtotal = (.75 + + .99 + (.5 * pizzaDiameter)) * 100;
            subtotal = Math.round(subtotal);
            subtotal = subtotal / 100;
        }
            
        lblSubtotalAns.setText("Subtotal: " + (String.valueOf(subtotal)));

        double tax = (subtotal * 0.13) * 100;
        tax = Math.round(tax);
        tax = tax / 100;
        lblTaxesAns.setText("Taxes(13%): " + (String.valueOf(tax)));

        double grandTotal = (subtotal + tax) * 100;
        grandTotal = Math.round(grandTotal);
        grandTotal = grandTotal / 100;
        lblGrandAns.setText("Grand Total: " + (String.valueOf(grandTotal)));
        
        if(pizzaDiameter > 0 && pizzaDiameter <= 20)
        {
            lblDesc.setText("We are going to make you a cute little pizza!");
        }
        else if(pizzaDiameter > 20 && pizzaDiameter <= 40)
        {
            lblDesc.setText("This will be delicious!");
        }
        else if(pizzaDiameter > 40)
        {
            lblDesc.setText("Whoa, big pizza! You might need a truck to get this home!");
        }

    }//GEN-LAST:event_btnCalcCostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPizzaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcCost;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblGrandAns;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblItem1;
    private javax.swing.JLabel lblSubtotalAns;
    private javax.swing.JLabel lblTaxesAns;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDiameterInput;
    // End of variables declaration//GEN-END:variables
}
