/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tykni9794
 */
public class FrmAvgCalcForm extends javax.swing.JFrame {

    /**
     * Creates new form FrmAvgCalcForm
     */
    public FrmAvgCalcForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblCourseMark1 = new javax.swing.JLabel();
        lblCourseMark2 = new javax.swing.JLabel();
        lblCourseMark3 = new javax.swing.JLabel();
        lblCourseMark4 = new javax.swing.JLabel();
        txtCourseMark1 = new javax.swing.JTextField();
        txtCourseMark2 = new javax.swing.JTextField();
        txtCourseMark3 = new javax.swing.JTextField();
        txtCourseMark4 = new javax.swing.JTextField();
        btnCalcAverage = new javax.swing.JButton();
        lblAnswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 0));
        lblTitle.setText("Course Mark Average Calculator");

        lblDesc.setText("Enter in your four course marks and click Calculate Average.");

        lblCourseMark1.setText("Course Mark 1:");

        lblCourseMark2.setText("Course Mark 2:");

        lblCourseMark3.setText("Course Mark 3:");

        lblCourseMark4.setText("Course Mark 4:");

        txtCourseMark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseMark1ActionPerformed(evt);
            }
        });

        txtCourseMark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseMark2ActionPerformed(evt);
            }
        });

        txtCourseMark3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseMark3ActionPerformed(evt);
            }
        });

        btnCalcAverage.setText("Calculate Average");
        btnCalcAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcAverageActionPerformed(evt);
            }
        });

        lblAnswer.setText("Average:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblDesc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseMark1)
                            .addComponent(lblCourseMark4)
                            .addComponent(lblCourseMark3)
                            .addComponent(lblCourseMark2))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseMark3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCourseMark2)
                                .addComponent(txtCourseMark1)
                                .addComponent(txtCourseMark4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcAverage)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblAnswer)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblDesc)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseMark1)
                    .addComponent(txtCourseMark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseMark2)
                    .addComponent(txtCourseMark3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseMark3)
                    .addComponent(txtCourseMark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseMark4)
                    .addComponent(txtCourseMark4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcAverage)
                .addGap(18, 18, 18)
                .addComponent(lblAnswer)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseMark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseMark1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseMark1ActionPerformed

    private void txtCourseMark3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseMark3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseMark3ActionPerformed

    private void txtCourseMark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseMark2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseMark2ActionPerformed

    private void btnCalcAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcAverageActionPerformed
        
        double mark1 = Integer.parseInt(txtCourseMark1.getText());
        double mark2 = Integer.parseInt(txtCourseMark2.getText());
        double mark3 = Integer.parseInt(txtCourseMark3.getText());
        double mark4 = Integer.parseInt(txtCourseMark4.getText());
        
        double averageAnswer = ((mark1 + mark2 + mark3 + mark4) / 4);
        averageAnswer = averageAnswer * 100;
        averageAnswer = Math.round(averageAnswer);
        averageAnswer = averageAnswer / 100;
        lblAnswer.setText(("Average: ") + String.valueOf(averageAnswer));
        
    }//GEN-LAST:event_btnCalcAverageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAvgCalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAvgCalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAvgCalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAvgCalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAvgCalcForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcAverage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblCourseMark1;
    private javax.swing.JLabel lblCourseMark2;
    private javax.swing.JLabel lblCourseMark3;
    private javax.swing.JLabel lblCourseMark4;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCourseMark1;
    private javax.swing.JTextField txtCourseMark2;
    private javax.swing.JTextField txtCourseMark3;
    private javax.swing.JTextField txtCourseMark4;
    // End of variables declaration//GEN-END:variables
}
